### ISSUE TITLE
BaseFragment - layout inflated in onCreate?

### ISSUE THREAD

**Issue by alexbusuioc** [general-mobile/kotlin-android-mvvm-starter#22]
Shouldn't the layout be inflated in onCreateView?

ps: nice starter code

**Comment by msayan** [comment]
Yes, you're right. Someone brokes the basefragment. Fixed with [this](https://github.com/general-mobile/kotlin-android-mvvm-starter/commit/4b60c167007dc70c6cd9233a768c75c26a9574a1) commit
